# Generated by Django 5.1.1 on 2024-09-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='more',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
